# recommended to overwrite name when using sealed-secrets
fullnameOverride: vpn
hostNetwork: false
image:
  repository: hwdsl2/ipsec-vpn-server
  tag: latest
  pullPolicy: Always

initContainer:
  image:
    repository: bash
    tag: alpine3.15

sealed_secrets: false

vpn:
  dns_name: vpn.example.com
  psk: your_presharedkey
  dns_srv1: 1.1.1.1
  dns_srv2: 1.0.0.1
# VPN_DNS_SRV2=1.0.0.1

users:
- username: vpn
  password: password

service:
  type: ClusterIP
  enabled: true
  externalIP: 
  ports:
    isakmp:
      name: vpn-isakmp
      port: 500
    ike:
      name: vpn-ike
      port: 4500

ingress:
  traefik:
    enabled: false
